language: cpp
branches:
  only:
    - master
    - openwrt
    - /^release*$/
compiler:
  - g++
  - clang++
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libcurl4-openssl-dev
      - python-yaml
env:
  global:
    - BUILD_DIR_NAME=build
before_install:
  - bash ./ci/install-cmake.sh
install:
- export CC="$CUSTOM_CC" CXX="$CUSTOM_CXX"
before_script:
  - bash ./ci/configure.sh
script:
  - bash ./ci/run.sh
sudo: false
